# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'YOUR_LICENSE_KEY_HERE'

  #Set the polling cycle (unit in seconds)
  poll: 60
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# AWS configuration.
#
aws:
  # Update with you AWS account keys:
  access_key: 'YOUR_AWS_ACCESS_KEY_HERE'
  secret_key: 'YOUR_AWS_SECRET_KEY_HERE'

  # AWS regions to query for metrics
  # regions:
  #  -
  #   us-east-1
  #  -
  #   us-east-2

# Agent Configuration:
#
agents:
  # this is where configuration for agents belongs
  redshift:
    host: 'REDSHIFT_HOST'
    port: 5439
    user: 'REDSHIFT_USER'
    password: 'REDSHIFT_PASSWORD'
    dbname: 'REDSHIFT_DATABASE_NAME'
    label: 'Redshift' # This label is optional and will default to the server hostname - it shows up in the NewRelic Web UI
    schema: 'production' #Redshift schema name you want the metrics for
    aws_cloudwatch:
      enabled: true
      cluster_identifiers:
        - db1
      node_id:
        - Leader
        - Compute-0
        - Compute-1
#       - Compute-N where N=0,1,2,..