# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: '101010101010'

  #Set the polling cycle (unit in seconds)
  poll: 60
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# Agent Configuration:
#
agents:
  # this is where configuration for agents belongs
  redshift:
    host: 'REDSHIFT_HOST'
    port: 5439
    user: 'REDSHIFT_USER'
    password: 'REDSHIFT_PASSWORD'
    dbname: 'REDSHIFT_DATABASE_NAME'
    label: 'Redshift' # This label is optional and will default to the server hostname - it shows up in the NewRelic Web UI
    schema: 'production' #Redshift schema name you want the metrics for